name: Kelly Test Site
favicon: null
layout_spectrum: 0.84499
typography_spectrum: 0.03893873910419643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7cad1'
    - '#ecf0f3'
    - '#161d15'
    - '#696e74'
    - '#454c44'
  brandStrength: 0.3347495999187231
  lightness: 0.8485371174756438
  saturation: 0.20894077653065324
  rhythmicContrast: 0.5
purpose: []
